CREATE TABLE `user_info` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `logonId` varchar(20) DEFAULT NULL COMMENT '登录ID',
  `nickName` varchar(50) DEFAULT NULL COMMENT '昵称',
  `userName` varchar(50) NOT NULL COMMENT '真实姓名',
  `cardNo` varchar(18) NOT NULL COMMENT '身份证号',
  `cardImg` varchar(50) DEFAULT NULL COMMENT '身份证照片',
  `sex` int(2) DEFAULT NULL COMMENT '性别:1:男;0:女',
  `papersTime` datetime DEFAULT NULL COMMENT '领证时间',
  `jobNumber` varchar(20) DEFAULT NULL,
  `mobile` varchar(15) DEFAULT NULL COMMENT '手机号',
  `password` varchar(32) DEFAULT NULL,
  `headImg` varchar(200) DEFAULT NULL COMMENT '头像',
  `papersImg` varchar(200) DEFAULT NULL COMMENT '驾驶证照片',
  `personalImg` varchar(200) DEFAULT NULL COMMENT '全身照',
  `balance` double(15,2) DEFAULT NULL,
  `emptypeType` int(2) DEFAULT NULL COMMENT '0:全职;1:兼职',
  `tcRatio` double(4,2) DEFAULT NULL COMMENT '提成比例;0表示不提成;10:表示提成10%',
  `djCnt` int(10) unsigned zerofill DEFAULT NULL COMMENT '代驾次数',
  `nativePlace` varchar(10) DEFAULT NULL COMMENT '籍贯',
  `address` varchar(200) DEFAULT NULL COMMENT '家庭住址',
  `emergencyContact` varchar(50) DEFAULT NULL COMMENT '紧急联系人',
  `emergencyContactTel` varchar(15) DEFAULT NULL COMMENT '紧急联系人电话',
  `workStatus` int(2) DEFAULT NULL COMMENT '工作状态：0:未上班；1：已上班；2：接单；3：忙碌',
  `userStatus` int(2) DEFAULT NULL COMMENT '会员状态：0：未审核；1：正常；2：冻结；3：解除合同;4：未通过审核',
  `applyTime` datetime DEFAULT NULL COMMENT '申请时间',
  `appVersion` varchar(10) DEFAULT NULL COMMENT 'app版本',
  `hireDate` datetime DEFAULT NULL COMMENT '入职时间',
  `location` varchar(100) DEFAULT NULL COMMENT '当前位置',
  `lon` double(18,14) DEFAULT NULL COMMENT '经度',
  `lat` double(18,14) DEFAULT NULL COMMENT '纬度',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `sysUnitId` varchar(32) DEFAULT NULL COMMENT '所属单位ID',
  `geo_code` char(12) DEFAULT NULL COMMENT 'geohash编码（精确度1.2m左右）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='驾驶员用户表';